import TimeBlock from "../Component/TimeBlock"

function TimeTable() {
  return (
    <main className="w-full  flex flex-col items-center">
      <h2 className="font-bold text-4xl">All Classes Time Table</h2>
      <span className="max-w-xl text-center">Lorem ipsum dolor sit amet consectetur  optio unde. Id cupiditate numquam officiis nulla veniam unde repudiandae consequuntur sapiente enim?</span>
      <div>
        <table>
          <thead>
            <tr>
              <th>Sunday</th>
              <th>Monday</th>
              <th>Tuesday</th>
              <th>Wednesday</th>
              <th>Thursday</th>
              <th>Friday</th>
              <th>Satrurday</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
            <tr>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
              <td>
                <TimeTable/>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  )
}

export default TimeTable
